/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hms;

import java.awt.CardLayout;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Connection;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author skg75
 */
public class doctor extends javax.swing.JFrame {

    /**
     * Creates new form doctor
     */
    public doctor(String doctorname) {
        initComponents();
        this.doctorname=doctorname;
        this.setExtendedState(MAXIMIZED_BOTH);
        CardLayout cl=new CardLayout();
        centralpanel.setLayout(cl);
        centralpanel.add(todayappointment,"todayappointment");
        centralpanel.add(patientlist,"patientlist");
        centralpanel.add(home,"home");
        cl.show(centralpanel, "home");
        tabletodayappointment();
        patientlisttable();
        datetime();
        jtotalpatient.setText(totalpatientcount());
        jtodaypatient.setText(todaypatientcount());
        jLabel54.setText("Welcome Doctor "+ doctorname);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        Home = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        Todayappointment = new javax.swing.JButton();
        Patientlist = new javax.swing.JButton();
        centralpanel = new javax.swing.JPanel();
        home = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabletodayappointment = new javax.swing.JTable();
        jLabel54 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jtotalpatient = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jtodaypatient = new javax.swing.JLabel();
        jlabeldate = new javax.swing.JLabel();
        todayappointment = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Puserid = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        Pname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Page = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Pdisease = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Pdiagnosis = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        Pprescription = new javax.swing.JTextArea();
        Psearch1 = new javax.swing.JButton();
        Asave = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        Pappointmenttime = new javax.swing.JTextField();
        patientlist = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        filterbydate = new com.toedter.calendar.JDateChooser();
        footer = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        header.setBackground(new java.awt.Color(21, 101, 192));

        jLabel52.setFont(new java.awt.Font("Nirmala UI", 1, 48)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("HOSPITAL MANAGEMENT SYSTEM");
        jLabel52.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1191, Short.MAX_VALUE)
            .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(headerLayout.createSequentialGroup()
                    .addGap(280, 280, 280)
                    .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(95, Short.MAX_VALUE)))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(headerLayout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(jLabel52)
                    .addContainerGap(18, Short.MAX_VALUE)))
        );

        getContentPane().add(header, java.awt.BorderLayout.PAGE_START);

        menu.setBackground(new java.awt.Color(13, 71, 161));
        menu.setPreferredSize(new java.awt.Dimension(240, 525));

        Home.setBackground(new java.awt.Color(25, 118, 210));
        Home.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Home.setForeground(new java.awt.Color(255, 255, 255));
        Home.setText("HOME");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });

        logout.setBackground(new java.awt.Color(25, 118, 210));
        logout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Log Out");
        logout.setPreferredSize(new java.awt.Dimension(153, 32));
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        Todayappointment.setBackground(new java.awt.Color(25, 118, 210));
        Todayappointment.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Todayappointment.setForeground(new java.awt.Color(255, 255, 255));
        Todayappointment.setText("PATIENT INFO");
        Todayappointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TodayappointmentActionPerformed(evt);
            }
        });

        Patientlist.setBackground(new java.awt.Color(25, 118, 210));
        Patientlist.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Patientlist.setForeground(new java.awt.Color(255, 255, 255));
        Patientlist.setText("ALL PATIENT");
        Patientlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientlistActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Todayappointment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Patientlist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Todayappointment, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Patientlist, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(486, Short.MAX_VALUE))
        );

        getContentPane().add(menu, java.awt.BorderLayout.LINE_START);

        centralpanel.setBackground(new java.awt.Color(51, 51, 0));
        centralpanel.setLayout(new java.awt.CardLayout());

        home.setBackground(new java.awt.Color(244, 246, 249));

        jPanel4.setBackground(new java.awt.Color(244, 246, 249));

        tabletodayappointment.setForeground(new java.awt.Color(255, 255, 255));
        tabletodayappointment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Patient ID", "Name", "Time slot", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabletodayappointment.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabletodayappointment.setGridColor(new java.awt.Color(220, 220, 220));
        tabletodayappointment.setShowGrid(true);
        jScrollPane2.setViewportView(tabletodayappointment);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );

        jLabel54.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel54.setText("Welcome , DOCTOR");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        jPanel1.setMaximumSize(new java.awt.Dimension(8, 120));
        jPanel1.setMinimumSize(new java.awt.Dimension(8, 120));
        jPanel1.setLayout(new java.awt.GridLayout(1, 2, 30, 0));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setText("Total Patient");

        jtotalpatient.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jtotalpatient.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jtotalpatient, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtotalpatient)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel23.setText("Today Patient");

        jtodaypatient.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jtodaypatient.setForeground(new java.awt.Color(64, 64, 64));
        jtodaypatient.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jtodaypatient, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtodaypatient, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);

        jlabeldate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlabeldate.setText("DATE");

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 333, Short.MAX_VALUE)
                .addComponent(jlabeldate, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(homeLayout.createSequentialGroup()
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homeLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(homeLayout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel54)
                    .addComponent(jlabeldate))
                .addGap(49, 49, 49)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        centralpanel.add(home, "card2");

        todayappointment.setBackground(new java.awt.Color(244, 246, 249));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Patient Id");

        Puserid.setPreferredSize(new java.awt.Dimension(64, 25));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setText("Patient Name");

        Pname.setEditable(false);
        Pname.setBackground(new java.awt.Color(255, 255, 255));
        Pname.setPreferredSize(new java.awt.Dimension(64, 25));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Age");

        Page.setEditable(false);
        Page.setBackground(new java.awt.Color(255, 255, 255));
        Page.setPreferredSize(new java.awt.Dimension(64, 25));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Disease");

        Pdisease.setEditable(false);
        Pdisease.setBackground(new java.awt.Color(255, 255, 255));
        Pdisease.setPreferredSize(new java.awt.Dimension(64, 25));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Diagnosis");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Prescription");

        Pdiagnosis.setPreferredSize(new java.awt.Dimension(64, 25));

        Pprescription.setColumns(20);
        Pprescription.setRows(5);
        jScrollPane3.setViewportView(Pprescription);

        Psearch1.setBackground(new java.awt.Color(25, 118, 210));
        Psearch1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Psearch1.setForeground(new java.awt.Color(255, 255, 255));
        Psearch1.setText("Search");
        Psearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Psearch1ActionPerformed(evt);
            }
        });

        Asave.setBackground(new java.awt.Color(25, 118, 210));
        Asave.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Asave.setForeground(new java.awt.Color(255, 255, 255));
        Asave.setText("SAVE");
        Asave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsaveActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Time Slot");

        Pappointmenttime.setEditable(false);
        Pappointmenttime.setBackground(new java.awt.Color(255, 255, 255));
        Pappointmenttime.setPreferredSize(new java.awt.Dimension(64, 25));

        javax.swing.GroupLayout todayappointmentLayout = new javax.swing.GroupLayout(todayappointment);
        todayappointment.setLayout(todayappointmentLayout);
        todayappointmentLayout.setHorizontalGroup(
            todayappointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(todayappointmentLayout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(Asave, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(todayappointmentLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addGroup(todayappointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(todayappointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(todayappointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(todayappointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(todayappointmentLayout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(59, 59, 59))
                                .addGroup(todayappointmentLayout.createSequentialGroup()
                                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(todayappointmentLayout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(todayappointmentLayout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(todayappointmentLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)))
                        .addGroup(todayappointmentLayout.createSequentialGroup()
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(75, 75, 75)))
                    .addGroup(todayappointmentLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111)))
                .addGroup(todayappointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(todayappointmentLayout.createSequentialGroup()
                        .addComponent(Pappointmenttime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(220, 220, 220))
                    .addGroup(todayappointmentLayout.createSequentialGroup()
                        .addGroup(todayappointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                            .addComponent(Pdiagnosis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Pdisease, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Page, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Pname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Puserid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE))
                        .addGap(48, 48, 48)
                        .addComponent(Psearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))))
        );
        todayappointmentLayout.setVerticalGroup(
            todayappointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(todayappointmentLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(todayappointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(todayappointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Puserid, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Psearch1)))
                .addGap(18, 18, 18)
                .addGroup(todayappointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pname, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(todayappointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Page, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(todayappointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pdisease, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(todayappointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pappointmenttime, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(todayappointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pdiagnosis, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(todayappointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(todayappointmentLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(todayappointmentLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addComponent(Asave)
                .addContainerGap(212, Short.MAX_VALUE))
        );

        centralpanel.add(todayappointment, "card3");

        patientlist.setBackground(new java.awt.Color(240, 248, 255));
        patientlist.setToolTipText("");

        jScrollPane1.setBackground(new java.awt.Color(51, 255, 51));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "USER ID", "NAME", "AGE", "DISEASE", "DIAGNOSIS", "PRESCRIPTION", "APPOINTMENT DATE", "TIME SLOT", "STATUS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(220, 220, 220));
        jTable1.setSelectionBackground(new java.awt.Color(173, 216, 230));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALL", "NAME", "PATIENT ID", "DISEASE", "DOCTOR", "DATE", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout patientlistLayout = new javax.swing.GroupLayout(patientlist);
        patientlist.setLayout(patientlistLayout);
        patientlistLayout.setHorizontalGroup(
            patientlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientlistLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(filterbydate, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 951, Short.MAX_VALUE)
        );
        patientlistLayout.setVerticalGroup(
            patientlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientlistLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(patientlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterbydate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        centralpanel.add(patientlist, "card4");

        getContentPane().add(centralpanel, java.awt.BorderLayout.CENTER);

        footer.setBackground(new java.awt.Color(13, 71, 161));
        footer.setPreferredSize(new java.awt.Dimension(1191, 39));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("© 2026 Hospital Management System | Version 1.0 | Developed by Shivam");

        javax.swing.GroupLayout footerLayout = new javax.swing.GroupLayout(footer);
        footer.setLayout(footerLayout);
        footerLayout.setHorizontalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerLayout.createSequentialGroup()
                .addContainerGap(416, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(257, 257, 257))
        );
        footerLayout.setVerticalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        getContentPane().add(footer, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private String doctorname;
    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        CardLayout cl=(CardLayout)centralpanel.getLayout();
        cl.show(centralpanel,"home");
        tabletodayappointment();
    }//GEN-LAST:event_HomeActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        System.exit(0);
    }//GEN-LAST:event_logoutActionPerformed

    private void TodayappointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TodayappointmentActionPerformed
       CardLayout cl=(CardLayout)centralpanel.getLayout();
       cl.show(centralpanel,"todayappointment");
    }//GEN-LAST:event_TodayappointmentActionPerformed

    private void PatientlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientlistActionPerformed
        CardLayout cl=(CardLayout)centralpanel.getLayout();
        cl.show(centralpanel,"patientlist");
        patientlisttable();
        filterbydate.getDateEditor().addPropertyChangeListener("date", e -> {
        filterpatientbydate(filterbydate.getDate());
    });
    }//GEN-LAST:event_PatientlistActionPerformed
     private String totalpatientcount()//shivam
    {
        String count="0";
        try
        {
            String sql="SELECT COUNT(*) FROM appointment ";
            String url="jdbc:mysql://localhost:3306/hospitalmana";
            Connection conn=DriverManager.getConnection(url,"root","root");
            PreparedStatement ps=conn.prepareStatement(sql);
            ResultSet rs=ps.executeQuery();
            if(rs.next())
            {
                count =rs.getString(1);
            }
            rs.close();
            ps.close();
            conn.close();
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,""+ex);
        }
        return count;
     }
    private String todaypatientcount()//shivam
    {
        String count="0";
        try
        {
            String sql="SELECT COUNT(*)FROM appointment WHERE appointment_date=CURDATE() AND status= 'BOOKED' ";
            String url="jdbc:mysql://localhost:3306/hospitalmana";
            Connection conn=DriverManager.getConnection(url,"root","root");
            PreparedStatement ps=conn.prepareStatement(sql);
            ResultSet rs=ps.executeQuery();
            if(rs.next())
            {
                count =rs.getString(1);
            }
            rs.close();
            ps.close();
            conn.close();
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,""+ex);
        }
        return count;
    }
    private void datetime()//shivam
    {
        DateTimeFormatter dtf=DateTimeFormatter.ofPattern("dd-MM-yyyy");
        jlabeldate.setText("DATE : "+LocalDate.now().format(dtf));
    }
    private void filterpatientbydate(java.util.Date selectedDate) //shivam
    {
        if (sorter == null) return;

        if (selectedDate == null) {
            sorter.setRowFilter(null); // show all
            return;
        }
        java.sql.Date sqlDate = new java.sql.Date(selectedDate.getTime());
        sorter.setRowFilter(new RowFilter<DefaultTableModel, Integer>() {
            @Override
            public boolean include(RowFilter.Entry<? extends DefaultTableModel, ? extends Integer> entry) {
                Object dateValue = entry.getValue(6); // appointment_date column
                if (dateValue == null) return false;
                return dateValue.toString().equals(sqlDate.toString());
            }
        });
    }

    private TableRowSorter<DefaultTableModel>sorter;
    private void tabletodayappointment()//shivam
    {
        try
        {    
            String sql="SELECT a.userid, p.name ,a.appointment_time ,a.status From appointment a "+
            "JOIN new_patient p ON a.userid = p.userid where a.appointment_date = CURDATE() AND a.status = 'BOOKED' AND a.doctor=? ";
            String url="jdbc:mysql://localhost:3306/hospitalmana";
            Connection conn=DriverManager.getConnection(url,"root","root");
            PreparedStatement ps=conn.prepareStatement(sql);
            ps.setString(1,doctorname);
            ResultSet rs=ps.executeQuery();
            DefaultTableModel model=(DefaultTableModel)tabletodayappointment.getModel();
            model.setRowCount(0);
            while(rs.next())
            {
                model.addRow(new Object[]
                {
                    rs.getString("userid"),
                    rs.getString("name"),
                    rs.getString("appointment_time"),
                    rs.getString("status")
                });
            }
            ps.close();
            conn.close();
            rs.close();            
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,ex);
        }
    }
    private void patientlisttable()//shivam
    {
        try 
        {
            String sql = "SELECT p.userid , p.name , p.age , p.disease , a.diagnosis, a.prescription, a.appointment_date ,"
            +" a.appointment_time , a.status FROM new_patient p "
            +" INNER JOIN appointment a ON p.userid = a.userid where a.doctor=? ";
            String url="jdbc:mysql://localhost:3306/hospitalmana";
            Connection conn = DriverManager.getConnection(url,"root","root");
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1,doctorname);
            ResultSet rs = ps.executeQuery();
            DefaultTableModel model =(DefaultTableModel) jTable1.getModel();
            sorter=new TableRowSorter<>(model);
            jTable1.setRowSorter(sorter);
            model.setRowCount(0); //clear old data
            while(rs.next())
            {
                model.addRow(new Object[] {
                    rs.getString("userid"),
                    rs.getString("name"),
                    rs.getInt("age"),
                    rs.getString("disease"),
                    rs.getString("diagnosis"),
                    rs.getString("prescription"),
                    rs.getDate("appointment_date"),
                    rs.getString("appointment_time"),
                    rs.getString("status")
                });
            } 
            rs.close();
            ps.close();
            conn.close();  
        } catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ""+ex);
        }
}
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void Psearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Psearch1ActionPerformed
        if(Puserid.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Please enter Patient id");
            return;
        }
        else
        {
            String userid=Puserid.getText().trim().toUpperCase();
            String Ause_reg=("^[A-Za-z]{3}[0-9]{3,4}$");
            if(Pattern.matches(Ause_reg,userid))
            {
                try
                {
                    String sql="SELECT p.name, p.age, p.disease , a.appointment_time, "+
                    " a.diagnosis , a.prescription FROM new_patient p "+
                    "LEFT JOIN appointment a on p.userid = a.userid where p.userid =?";
                    String url="jdbc:mysql://localhost:3306/hospitalmana";
                    Connection conn=DriverManager.getConnection(url,"root","root");
                    PreparedStatement ps=conn.prepareStatement(sql);
                    ps.setString(1,Puserid.getText());
                    ResultSet rs=ps.executeQuery();
                    if(rs.next())
                    {
                        // JOptionPane.showMessageDialog(null, "data found");
                        Pname.setText(rs.getString("name"));
                        Page.setText(rs.getString("age"));
                        Pdisease.setText(rs.getString("disease"));
                        Pappointmenttime.setText(rs.getString("appointment_time"));
                        Pdiagnosis.setText(rs.getString("diagnosis"));
                        Pprescription.setText(rs.getString("prescription"));
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null,"Data not found");
                    }
                    rs.close();
                    ps.close();
                    conn.close();
                }
                catch(Exception ex)
                {
                    JOptionPane.showMessageDialog(null,""+ex);
                }
            }
        }
    }//GEN-LAST:event_Psearch1ActionPerformed

    private void AsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsaveActionPerformed
        if(Puserid.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null," Please check all value");
            return ;
        }
        try
        {
            String sql="UPDATE appointment SET diagnosis=? ,prescription=?, status='COMPLETED' "
            +"WHERE userid=? AND appointment_date= CURDATE()";
            String url="jdbc:mysql://localhost:3306/hospitalmana";
            Connection conn=DriverManager.getConnection(url,"root","root");
            PreparedStatement ps=conn.prepareStatement(sql);
            ps.setString(1,Pdiagnosis.getText());
            ps.setString(2,Pprescription.getText());
            ps.setString(3,Puserid.getText().toUpperCase());
            int a=ps.executeUpdate();
            if(a>0)
            {
                JOptionPane.showMessageDialog(null,"SAVED ");
                Puserid.setText(null);
                Pname.setText(null);
                Pdisease.setText(null);
                Pdiagnosis.setText(null);
                Pprescription.setText(null);
            }
            ps.close();
            conn.close();
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null," It  is already saved. "+ex);
        }

    }//GEN-LAST:event_AsaveActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new doctor().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Asave;
    private javax.swing.JButton Home;
    private javax.swing.JTextField Page;
    private javax.swing.JTextField Pappointmenttime;
    private javax.swing.JButton Patientlist;
    private javax.swing.JTextField Pdiagnosis;
    private javax.swing.JTextField Pdisease;
    private javax.swing.JTextField Pname;
    private javax.swing.JTextArea Pprescription;
    private javax.swing.JButton Psearch1;
    private javax.swing.JTextField Puserid;
    private javax.swing.JButton Todayappointment;
    private javax.swing.JPanel centralpanel;
    private com.toedter.calendar.JDateChooser filterbydate;
    private javax.swing.JPanel footer;
    private javax.swing.JPanel header;
    private javax.swing.JPanel home;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jlabeldate;
    private javax.swing.JLabel jtodaypatient;
    private javax.swing.JLabel jtotalpatient;
    private javax.swing.JButton logout;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel patientlist;
    private javax.swing.JTable tabletodayappointment;
    private javax.swing.JPanel todayappointment;
    // End of variables declaration//GEN-END:variables
}
