/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hms;

import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
/**
 *
 * @author skg75
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Lrole = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        Lpassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        Luserid = new javax.swing.JTextField();
        Lforgetpass = new javax.swing.JButton();
        Lsignin = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        footer = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        header.setBackground(new java.awt.Color(13, 71, 161));
        header.setPreferredSize(new java.awt.Dimension(1445, 140));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("HOSPITAL MANAGEMENT SYSTEM");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel6.setIcon(new javax.swing.ImageIcon("Q:\\onedrive\\Pictures\\logohmss.png")); // NOI18N

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1045, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        getContentPane().add(header, java.awt.BorderLayout.NORTH);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 8));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel1.setText("Role");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 41, 68, -1));

        Lrole.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Lrole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Role", "Admin", "Doctor", "Receptionist", "Ward Boy", "Guard" }));
        Lrole.setFocusable(false);
        jPanel3.add(Lrole, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 72, 282, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel2.setText("User Id");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 109, 98, -1));

        Lpassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Lpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LpasswordActionPerformed(evt);
            }
        });
        jPanel3.add(Lpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 282, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel3.setText("Password");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 183, 98, -1));

        Luserid.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Luserid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LuseridActionPerformed(evt);
            }
        });
        jPanel3.add(Luserid, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 282, -1));

        Lforgetpass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Lforgetpass.setForeground(new java.awt.Color(0, 0, 255));
        Lforgetpass.setText("Forget Password");
        Lforgetpass.setBorder(null);
        Lforgetpass.setBorderPainted(false);
        Lforgetpass.setContentAreaFilled(false);
        Lforgetpass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Lforgetpass.setFocusPainted(false);
        Lforgetpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LforgetpassActionPerformed(evt);
            }
        });
        jPanel3.add(Lforgetpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, -1));

        Lsignin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Lsignin.setText("Sign In");
        Lsignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LsigninActionPerformed(evt);
            }
        });
        jPanel3.add(Lsignin, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 110, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/image/Screenshot 2026-01-18 151031.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(185, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(268, 268, 268))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        footer.setBackground(new java.awt.Color(13, 71, 161));
        footer.setPreferredSize(new java.awt.Dimension(1191, 39));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("© 2026 Hospital Management System | Version 1.0 | Developed by Shivam");

        javax.swing.GroupLayout footerLayout = new javax.swing.GroupLayout(footer);
        footer.setLayout(footerLayout);
        footerLayout.setHorizontalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerLayout.createSequentialGroup()
                .addContainerGap(439, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(431, 431, 431))
        );
        footerLayout.setVerticalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        getContentPane().add(footer, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LforgetpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LforgetpassActionPerformed
      forgetpassword fp=new forgetpassword();
      fp.setVisible(true);
      this.setVisible(false);
    }//GEN-LAST:event_LforgetpassActionPerformed

    private void LsigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LsigninActionPerformed
        if(Lrole.getSelectedItem().toString().equals("Select Role")||
           Luserid.getText().trim().isEmpty()||
           Lpassword.getPassword().length==0)
        {
            JOptionPane.showMessageDialog(null,"Enter the all value");
        }
        else
        {
            try
            {   String role = Lrole.getSelectedItem().toString();
                String userid = Luserid.getText().trim();
                char p[]=Lpassword.getPassword();
                String pass=String.valueOf(p);
                String sql="SELECT *from staff_registration where role=? and userid=? and password=? and leavingdate is null";
                String url="jdbc:mysql://localhost:3306/hospitalmana";
                Connection conn =DriverManager.getConnection(url,"root","root");
                PreparedStatement ps=conn.prepareStatement(sql);
                ps.setString(1,role);
                ps.setString(2,userid);
                ps.setString(3,pass);
                ResultSet rs=ps.executeQuery();
                if(rs.next())
                {
                    JOptionPane.showMessageDialog(null, "Login Successfully");
                    this.dispose();
                    if(role.equals("Admin"))
                    {
                        new admin().setVisible(true);
                    }
                    else if(role.equals("Doctor"))
                    {
                        String doctorname=rs.getString("name");
                        new doctor(doctorname).setVisible(true);
                    }
                    else if(role.equals("Receptionist"))
                    {
                        new receptionist().setVisible(true);
                    }
                 rs.close();
                 ps.close();
                 conn.close();
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Please Enter Right Information");
                    Lrole.setSelectedIndex(0);
                    Luserid.setText(null);
                    Lpassword.setText(null);
                }    
            }
            catch(Exception ex)
            {
                JOptionPane.showMessageDialog(null," "+ex);
            }
        }
    }//GEN-LAST:event_LsigninActionPerformed

    private void LpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LpasswordActionPerformed

    private void LuseridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LuseridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LuseridActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Lforgetpass;
    private javax.swing.JPasswordField Lpassword;
    private javax.swing.JComboBox<String> Lrole;
    private javax.swing.JButton Lsignin;
    private javax.swing.JTextField Luserid;
    private javax.swing.JPanel footer;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
