/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hms;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import java.util.regex.Pattern;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDate;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.RowFilter;
import java.time.format.DateTimeFormatter;
/**
 *
 * @author skg75
 */
public class receptionist extends javax.swing.JFrame {

    /**
     * Creates new form receptionist
     */
    public receptionist() {
        initComponents();
         this.setExtendedState(MAXIMIZED_BOTH);
         CardLayout cl=new CardLayout();
        centralpanel.setLayout(cl);
        centralpanel.add(home,"home");        
        centralpanel.add(newpatient,"newpatient");
        centralpanel.add(patientlist,"patientlist");
        centralpanel.add(appointment,"appointment");
        centralpanel.add(searchupdate,"searchupdate");
        cl.show(centralpanel, "home");
        datetime();
        jtodaypatient.setText(todaypatientcount());
        jtotalpatient.setText(totalpatientcount());
        tabletodayappointment();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        header = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        Home = new javax.swing.JButton();
        Newpatient = new javax.swing.JButton();
        Searchupdate = new javax.swing.JButton();
        Patientlist = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        Appointment = new javax.swing.JButton();
        centralpanel = new javax.swing.JPanel();
        newpatient = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Pname = new javax.swing.JTextField();
        Page = new javax.swing.JTextField();
        Pfather = new javax.swing.JTextField();
        Paadhar = new javax.swing.JTextField();
        Pcontact = new javax.swing.JTextField();
        Male = new javax.swing.JRadioButton();
        Female = new javax.swing.JRadioButton();
        Pdisease = new javax.swing.JTextField();
        Save = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        Pregistrationd = new com.toedter.calendar.JDateChooser();
        jLabel20 = new javax.swing.JLabel();
        Puserid = new javax.swing.JTextField();
        Padd = new javax.swing.JLabel();
        Paddress = new javax.swing.JTextField();
        patientlist = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        filterbydate = new com.toedter.calendar.JDateChooser();
        appointment = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        Auserid = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        Aname = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        Psearch1 = new javax.swing.JButton();
        Aappointmentdate = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Asave = new javax.swing.JButton();
        Aappointmenttime = new javax.swing.JComboBox<>();
        Update = new javax.swing.JButton();
        Acancel = new javax.swing.JButton();
        Adoctor = new javax.swing.JComboBox<>();
        home = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jlabeldate = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jtotalpatient = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jtodaypatient = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabletodayappointment = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        searchupdate = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        Sname = new javax.swing.JTextField();
        Sage = new javax.swing.JTextField();
        Sfather = new javax.swing.JTextField();
        Saadhar = new javax.swing.JTextField();
        Scontact = new javax.swing.JTextField();
        MALE = new javax.swing.JRadioButton();
        FEMALE = new javax.swing.JRadioButton();
        Sdisease = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        Clear1 = new javax.swing.JButton();
        Sregistrationd = new com.toedter.calendar.JDateChooser();
        jLabel33 = new javax.swing.JLabel();
        Suserid = new javax.swing.JTextField();
        Padd1 = new javax.swing.JLabel();
        Saddress = new javax.swing.JTextField();
        Ssearch = new javax.swing.JButton();
        footer = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        header.setBackground(new java.awt.Color(13, 71, 161));

        jLabel52.setFont(new java.awt.Font("Nirmala UI", 1, 48)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("HOSPITAL MANAGEMENT SYSTEM");
        jLabel52.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(310, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel52)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(header, java.awt.BorderLayout.PAGE_START);

        menu.setBackground(new java.awt.Color(32, 32, 32));
        menu.setPreferredSize(new java.awt.Dimension(200, 524));

        Home.setBackground(new java.awt.Color(240, 240, 240));
        Home.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Home.setText("HOME");
        Home.setBorderPainted(false);
        Home.setFocusPainted(false);
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });

        Newpatient.setBackground(new java.awt.Color(240, 240, 240));
        Newpatient.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Newpatient.setText("NEW PATIENT");
        Newpatient.setBorderPainted(false);
        Newpatient.setFocusPainted(false);
        Newpatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewpatientActionPerformed(evt);
            }
        });

        Searchupdate.setBackground(new java.awt.Color(240, 240, 240));
        Searchupdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Searchupdate.setText("SEARCH/UPDATE");
        Searchupdate.setBorderPainted(false);
        Searchupdate.setFocusPainted(false);
        Searchupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchupdateActionPerformed(evt);
            }
        });

        Patientlist.setBackground(new java.awt.Color(240, 240, 240));
        Patientlist.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Patientlist.setText("PATIENT LIST");
        Patientlist.setFocusPainted(false);
        Patientlist.setPreferredSize(new java.awt.Dimension(153, 32));
        Patientlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientlistActionPerformed(evt);
            }
        });

        logout.setBackground(new java.awt.Color(240, 240, 240));
        logout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        logout.setText("LOG OUT");
        logout.setBorderPainted(false);
        logout.setFocusPainted(false);
        logout.setPreferredSize(new java.awt.Dimension(153, 32));
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        Appointment.setBackground(new java.awt.Color(240, 240, 240));
        Appointment.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Appointment.setText("APPOINTMENT");
        Appointment.setBorderPainted(false);
        Appointment.setFocusPainted(false);
        Appointment.setPreferredSize(new java.awt.Dimension(153, 32));
        Appointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppointmentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Newpatient, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Searchupdate, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Patientlist, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Appointment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Newpatient, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Searchupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Patientlist, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(Appointment, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(419, Short.MAX_VALUE))
        );

        getContentPane().add(menu, java.awt.BorderLayout.LINE_START);

        centralpanel.setBackground(new java.awt.Color(204, 204, 255));
        centralpanel.setLayout(new java.awt.CardLayout());

        newpatient.setBackground(new java.awt.Color(255, 255, 255));
        newpatient.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Patient Id");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Father Name");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Aadhar Number");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Gender ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Contact No.");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Age");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Disease");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Registration Date");

        Pname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Pname.setPreferredSize(new java.awt.Dimension(64, 25));

        Page.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Page.setPreferredSize(new java.awt.Dimension(64, 25));

        Pfather.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Pfather.setPreferredSize(new java.awt.Dimension(64, 25));
        Pfather.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PfatherActionPerformed(evt);
            }
        });

        Paadhar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Paadhar.setPreferredSize(new java.awt.Dimension(64, 25));

        Pcontact.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Pcontact.setPreferredSize(new java.awt.Dimension(64, 25));

        buttonGroup1.add(Male);
        Male.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Male.setText("Male");
        Male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleActionPerformed(evt);
            }
        });

        buttonGroup1.add(Female);
        Female.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Female.setText("Female");
        Female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemaleActionPerformed(evt);
            }
        });

        Pdisease.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Pdisease.setPreferredSize(new java.awt.Dimension(64, 25));

        Save.setBackground(new java.awt.Color(52, 152, 219));
        Save.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        Save.setForeground(new java.awt.Color(255, 255, 255));
        Save.setText("SAVE");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        Clear.setBackground(new java.awt.Color(52, 152, 219));
        Clear.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        Clear.setForeground(new java.awt.Color(255, 255, 255));
        Clear.setText("CLEAR");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        Pregistrationd.setDoubleBuffered(false);
        Pregistrationd.setEnabled(false);
        Pregistrationd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setText("Patient Name");

        Puserid.setEditable(false);
        Puserid.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Puserid.setPreferredSize(new java.awt.Dimension(64, 25));

        Padd.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Padd.setText("Address");

        Paddress.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Paddress.setPreferredSize(new java.awt.Dimension(64, 25));

        javax.swing.GroupLayout newpatientLayout = new javax.swing.GroupLayout(newpatient);
        newpatient.setLayout(newpatientLayout);
        newpatientLayout.setHorizontalGroup(
            newpatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newpatientLayout.createSequentialGroup()
                .addContainerGap(295, Short.MAX_VALUE)
                .addGroup(newpatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newpatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Padd, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(newpatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Pcontact, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                    .addComponent(Paadhar, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                    .addComponent(Pname, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                    .addComponent(Page, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                    .addComponent(Pfather, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                    .addGroup(newpatientLayout.createSequentialGroup()
                        .addComponent(Male, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(Female, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Pdisease, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                    .addComponent(Pregistrationd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Puserid, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                    .addComponent(Paddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 318, Short.MAX_VALUE))
            .addGroup(newpatientLayout.createSequentialGroup()
                .addGap(381, 381, 381)
                .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126)
                .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        newpatientLayout.setVerticalGroup(
            newpatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newpatientLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(newpatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Puserid, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newpatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pname, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newpatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pfather, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newpatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(newpatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Male)
                        .addComponent(Female)))
                .addGap(18, 18, 18)
                .addGroup(newpatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Page, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newpatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Pcontact, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newpatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Padd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Paddress, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newpatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Paadhar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newpatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pdisease, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newpatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pregistrationd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(newpatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Save)
                    .addComponent(Clear))
                .addGap(166, 166, 166))
        );

        centralpanel.add(newpatient, "card3");

        patientlist.setBackground(new java.awt.Color(240, 248, 255));
        patientlist.setToolTipText("");

        jScrollPane1.setBackground(new java.awt.Color(51, 255, 51));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "USER ID", "NAME", "CONTACT", "AGE", "AADHAR", "DOCTOR", "APPOINTMENT DATE", "TIME SLOT", "STATUS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(220, 220, 220));
        jTable1.setSelectionBackground(new java.awt.Color(173, 216, 230));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout patientlistLayout = new javax.swing.GroupLayout(patientlist);
        patientlist.setLayout(patientlistLayout);
        patientlistLayout.setHorizontalGroup(
            patientlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1206, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, patientlistLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(filterbydate, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        patientlistLayout.setVerticalGroup(
            patientlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientlistLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(filterbydate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        centralpanel.add(patientlist, "card4");

        appointment.setBackground(new java.awt.Color(255, 250, 240));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Patient Id");

        Auserid.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Auserid.setPreferredSize(new java.awt.Dimension(64, 25));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setText("Patient Name");

        Aname.setEditable(false);
        Aname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Aname.setPreferredSize(new java.awt.Dimension(64, 25));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("Doctor");

        Psearch1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        Psearch1.setText("Search");
        Psearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Psearch1ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("Date");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setText("Time Slot");

        Asave.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        Asave.setText("SAVE");
        Asave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsaveActionPerformed(evt);
            }
        });

        Aappointmenttime.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Aappointmenttime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select Time Slot--", "09:00 - 09:15", "09:15 - 09:30", "09:30 - 09:45", "09:45 - 10:00", "10:00 - 10:15", "10:15 - 10:30", "10:30 - 10:45", "10:45 - 11:00", "11:00 - 11:15", "11:15 - 11:30", "11:30 - 11:45", "11:45 - 12:00", "01:00 - 01:15", "01:15 - 01:30", "01:30 - 01:45", "01:45 - 02:00" }));

        Update.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Update.setText("CHANGE APPOINTMENT");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Acancel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Acancel.setText("CANCEL ");
        Acancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcancelActionPerformed(evt);
            }
        });

        Adoctor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Adoctor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select Doctor--" }));
        Adoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdoctorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout appointmentLayout = new javax.swing.GroupLayout(appointment);
        appointment.setLayout(appointmentLayout);
        appointmentLayout.setHorizontalGroup(
            appointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, appointmentLayout.createSequentialGroup()
                .addContainerGap(190, Short.MAX_VALUE)
                .addGroup(appointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(appointmentLayout.createSequentialGroup()
                        .addComponent(Asave, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)
                        .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addComponent(Acancel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, appointmentLayout.createSequentialGroup()
                        .addGroup(appointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(appointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74)
                        .addGroup(appointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Auserid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Aname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Aappointmentdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                            .addComponent(Aappointmenttime, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Adoctor, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(69, 69, 69)
                        .addComponent(Psearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(235, 235, 235))))
        );
        appointmentLayout.setVerticalGroup(
            appointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(appointmentLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(appointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Auserid, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Psearch1))
                .addGap(18, 18, 18)
                .addGroup(appointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Aname, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(appointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Adoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(appointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Aappointmentdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(appointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Aappointmenttime, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(142, 142, 142)
                .addGroup(appointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Acancel)
                    .addComponent(Asave))
                .addContainerGap(263, Short.MAX_VALUE))
        );

        centralpanel.add(appointment, "card6");

        home.setBackground(new java.awt.Color(244, 246, 249));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setText("Welcome, Receptionist");

        jlabeldate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlabeldate.setText("DATE");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        jPanel1.setMaximumSize(new java.awt.Dimension(8, 120));
        jPanel1.setMinimumSize(new java.awt.Dimension(8, 120));
        jPanel1.setLayout(new java.awt.GridLayout(1, 2, 30, 0));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setText("Total Patient");

        jtotalpatient.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jtotalpatient.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jtotalpatient, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtotalpatient)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel23.setText("Today Patient");

        jtodaypatient.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jtodaypatient.setForeground(new java.awt.Color(64, 64, 64));
        jtodaypatient.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jtodaypatient, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtodaypatient, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(244, 246, 249));

        tabletodayappointment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Patient ID", "Name", "Doctor", "Time slot"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabletodayappointment.setGridColor(new java.awt.Color(220, 220, 220));
        tabletodayappointment.setShowGrid(true);
        jScrollPane2.setViewportView(tabletodayappointment);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Today patient");

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 767, Short.MAX_VALUE)
                        .addComponent(jlabeldate, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(homeLayout.createSequentialGroup()
                        .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(homeLayout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(homeLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jlabeldate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(68, 68, 68))
        );

        centralpanel.add(home, "card2");

        searchupdate.setBackground(new java.awt.Color(255, 255, 255));
        searchupdate.setToolTipText("");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel25.setText("Patient Id");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel26.setText("Father Name");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel27.setText("Aadhar Number");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel28.setText("Gender ");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel29.setText("Contact No.");

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel30.setText("Age");

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel31.setText("Disease");

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel32.setText("Registration Date");

        Sname.setEditable(false);
        Sname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Sname.setPreferredSize(new java.awt.Dimension(64, 25));

        Sage.setEditable(false);
        Sage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Sage.setPreferredSize(new java.awt.Dimension(64, 25));

        Sfather.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Sfather.setPreferredSize(new java.awt.Dimension(64, 25));
        Sfather.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SfatherActionPerformed(evt);
            }
        });

        Saadhar.setEditable(false);
        Saadhar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Saadhar.setPreferredSize(new java.awt.Dimension(64, 25));

        Scontact.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Scontact.setPreferredSize(new java.awt.Dimension(64, 25));

        buttonGroup2.add(MALE);
        MALE.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MALE.setText("Male");
        MALE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MALEActionPerformed(evt);
            }
        });

        buttonGroup2.add(FEMALE);
        FEMALE.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        FEMALE.setText("Female");
        FEMALE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FEMALEActionPerformed(evt);
            }
        });

        Sdisease.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Sdisease.setPreferredSize(new java.awt.Dimension(64, 25));

        update.setBackground(new java.awt.Color(52, 152, 219));
        update.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        Clear1.setBackground(new java.awt.Color(52, 152, 219));
        Clear1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        Clear1.setForeground(new java.awt.Color(255, 255, 255));
        Clear1.setText("CLEAR");
        Clear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clear1ActionPerformed(evt);
            }
        });

        Sregistrationd.setDoubleBuffered(false);
        Sregistrationd.setEnabled(false);
        Sregistrationd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel33.setText("Patient Name");

        Suserid.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Suserid.setPreferredSize(new java.awt.Dimension(64, 25));

        Padd1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Padd1.setText("Address");

        Saddress.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Saddress.setPreferredSize(new java.awt.Dimension(64, 25));

        Ssearch.setBackground(new java.awt.Color(25, 118, 210));
        Ssearch.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        Ssearch.setForeground(new java.awt.Color(255, 255, 255));
        Ssearch.setText("SEARCH");
        Ssearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SsearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchupdateLayout = new javax.swing.GroupLayout(searchupdate);
        searchupdate.setLayout(searchupdateLayout);
        searchupdateLayout.setHorizontalGroup(
            searchupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchupdateLayout.createSequentialGroup()
                .addContainerGap(295, Short.MAX_VALUE)
                .addGroup(searchupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchupdateLayout.createSequentialGroup()
                        .addGroup(searchupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(searchupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Padd1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(searchupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(searchupdateLayout.createSequentialGroup()
                                .addGroup(searchupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Scontact, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                                    .addComponent(Saadhar, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                                    .addComponent(Sname, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                                    .addComponent(Sage, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                                    .addComponent(Sfather, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                                    .addGroup(searchupdateLayout.createSequentialGroup()
                                        .addComponent(MALE, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(FEMALE, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Sdisease, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                                    .addComponent(Sregistrationd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Suserid, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE))
                                .addGap(73, 73, 73)
                                .addComponent(Ssearch))
                            .addComponent(Saddress, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(searchupdateLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132)
                        .addComponent(Clear1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 145, Short.MAX_VALUE))
        );
        searchupdateLayout.setVerticalGroup(
            searchupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchupdateLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(searchupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(searchupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Suserid, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Ssearch)))
                .addGap(18, 18, 18)
                .addGroup(searchupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sname, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(searchupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sfather, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(searchupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(searchupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MALE)
                        .addComponent(FEMALE)))
                .addGap(18, 18, 18)
                .addGroup(searchupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sage, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(searchupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Scontact, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(searchupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchupdateLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(Padd1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(searchupdateLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Saddress, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(searchupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Saadhar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(searchupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sdisease, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(searchupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sregistrationd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addGroup(searchupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(update)
                    .addComponent(Clear1)))
        );

        centralpanel.add(searchupdate, "card3");

        getContentPane().add(centralpanel, java.awt.BorderLayout.CENTER);

        footer.setBackground(new java.awt.Color(13, 71, 161));
        footer.setPreferredSize(new java.awt.Dimension(1191, 35));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("© 2026 Hospital Management System | Version 1.0 | Developed by Shivam");

        javax.swing.GroupLayout footerLayout = new javax.swing.GroupLayout(footer);
        footer.setLayout(footerLayout);
        footerLayout.setHorizontalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerLayout.createSequentialGroup()
                .addContainerGap(631, Short.MAX_VALUE)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(257, 257, 257))
        );
        footerLayout.setVerticalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        getContentPane().add(footer, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private TableRowSorter<DefaultTableModel>sorter;//shivam
    private void filterpatientbydate(java.util.Date selectedDate) //shivam
    {
    if (sorter == null) return;

    if (selectedDate == null) {
        sorter.setRowFilter(null); // show all
        return;
    }
    java.sql.Date sqlDate = new java.sql.Date(selectedDate.getTime());
    sorter.setRowFilter(new RowFilter<DefaultTableModel, Integer>() {
        @Override
        public boolean include(Entry<? extends DefaultTableModel, ? extends Integer> entry) {
            Object dateValue = entry.getValue(6); // appointment_date column
            if (dateValue == null) return false;
            return dateValue.toString().equals(sqlDate.toString());
        }
    });
}


    private void tabletodayappointment()//shivam
    {
        try
        {
            String sql="SELECT a.userid, p.name , a.doctor , a.appointment_time From appointment a "+
                    "JOIN new_patient p ON a.userid = p.userid where a.appointment_date = CURDATE() AND status = 'BOOKED' ";
            String url="jdbc:mysql://localhost:3306/hospitalmana";
            Connection conn=DriverManager.getConnection(url,"root","root");
            PreparedStatement ps=conn.prepareStatement(sql);
            ResultSet rs=ps.executeQuery();
            DefaultTableModel model=(DefaultTableModel)tabletodayappointment.getModel();
            model.setRowCount(0);
            while(rs.next())
            {
                model.addRow(new Object[]
                {
                    rs.getString("userid"),
                    rs.getString("name"),
                    rs.getString("doctor"),
                    rs.getString("appointment_time")
                    
                    
                });
            }
            ps.close();
            conn.close();
            rs.close();
            
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,ex);
        }
    }
    private void datetime()//shivam
    {
        DateTimeFormatter dtf=DateTimeFormatter.ofPattern("dd-MM-yyyy");
        jlabeldate.setText("DATE : "+LocalDate.now().format(dtf));
    }
     private String totalpatientcount()//shivam
    {
        String count="0";
        try
        {
            String sql="SELECT COUNT(*) FROM new_patient ";
            String url="jdbc:mysql://localhost:3306/hospitalmana";
            Connection conn=DriverManager.getConnection(url,"root","root");
            PreparedStatement ps=conn.prepareStatement(sql);
            ResultSet rs=ps.executeQuery();
            if(rs.next())
            {
                count =rs.getString(1);
            }
            rs.close();
            ps.close();
            conn.close();
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,""+ex);
        }
        return count;
    }
    private String todaypatientcount()//shivam
    {
        String count="0";
        try
        {
            String sql="SELECT COUNT(*)FROM appointment WHERE appointment_date=CURDATE() AND status= 'BOOKED'";
            String url="jdbc:mysql://localhost:3306/hospitalmana";
            Connection conn=DriverManager.getConnection(url,"root","root");
            PreparedStatement ps=conn.prepareStatement(sql);
            ResultSet rs=ps.executeQuery();
            if(rs.next())
            {
                count =rs.getString(1);
            }
            rs.close();
            ps.close();
            conn.close();
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,""+ex);
        }
        return count;
    }
    private void doctorcombobox()
    {
        try
        {
            String sql="Select name from staff_registration where role='Doctor' AND leavingdate is null";
            String url="jdbc:mysql://localhost:3306/hospitalmana";
            Connection conn=DriverManager.getConnection(url,"root","root");
            PreparedStatement ps=conn.prepareStatement(sql);
            ResultSet rs=ps.executeQuery();
            Adoctor.removeAllItems();
            while(rs.next())
            {
                Adoctor.addItem(rs.getString("name"));
            }
            rs.close();
            ps.close();
            conn.close();
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,""+ex);
        }
    }
    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        CardLayout cl=(CardLayout)centralpanel.getLayout();
        cl.show(centralpanel,"home");
        tabletodayappointment();
        jtotalpatient.setText(totalpatientcount());
        jtodaypatient.setText(todaypatientcount());
    }//GEN-LAST:event_HomeActionPerformed

    private void NewpatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewpatientActionPerformed
        CardLayout cl=(CardLayout)centralpanel.getLayout();
        cl.show(centralpanel,"newpatient");
        Pregistrationd.setDate(new java.util.Date());
    }//GEN-LAST:event_NewpatientActionPerformed

    private void PfatherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PfatherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PfatherActionPerformed

    private void Patientlisttable()//shivam
    {
    try 
    {
        String sql = "SELECT p.userid , p.name , p.contact, p.age ,p.aadhar, a.doctor , a.appointment_date ,"
        +" a.appointment_time , a.status FROM new_patient p "
        +" LEFT JOIN appointment a ON p.userid = a.userid ";
        String url="jdbc:mysql://localhost:3306/hospitalmana";
        Connection conn = DriverManager.getConnection(url,"root","root");
        PreparedStatement ps = conn.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();
        DefaultTableModel model =(DefaultTableModel) jTable1.getModel();
        sorter=new TableRowSorter<>(model);
        jTable1.setRowSorter(sorter);
        model.setRowCount(0); //clear old data
        while(rs.next())
        {
            model.addRow(new Object[] {
                rs.getString("userid"),
                rs.getString("name"),
                rs.getString("contact"),
                rs.getInt("age"),
                rs.getString("aadhar"),
                rs.getString("doctor"),
                rs.getDate("appointment_date"),
                rs.getString("appointment_time"),
                rs.getString("status")
            });
        } 
        rs.close();
        ps.close();
        conn.close();  
    } catch(Exception ex)
    {
        JOptionPane.showMessageDialog(null, ""+ex);
    }
}

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        if(Pname.getText().length()<=0||
           Page.getText().length()<=0||
           Pcontact.getText().length()<=0||
           Paddress.getText().length()<=0||
           Paadhar.getText().length()<=0)
        {
            JOptionPane.showMessageDialog(null,"Please enter the essential information");
        }
        else
        {
            Puserid.setText(generatepatientid());
            try
            {
                String pname=Pname.getText().trim().toUpperCase();
                String pnam_reg=("^[a-zA-Z ]+$");
                if(!(Pattern.matches(pnam_reg,pname)))
                {
                    JOptionPane.showMessageDialog(null,"Please enter the name");
                    Pname.requestFocus();
                    return;
                }
                String pfather=Pfather.getText().trim().toUpperCase();
                if(!(Pattern.matches(pnam_reg,pfather )))
                {
                    JOptionPane.showMessageDialog(null,"Please enter a valid name ");
                    Pfather.requestFocus();
                    return;
                }
                if(!Male.isSelected()&&!Female.isSelected())
                {
                    JOptionPane.showMessageDialog(null,"Please select the Gender");
                    return;
                }
                String page=Page.getText().trim();
                String page_reg=("^[0-9]{1,3}$");
                if(!(Pattern.matches(page_reg, page)))
                {
                    JOptionPane.showMessageDialog(null,"Please enter right age");
                    Page.requestFocus();
                    return;
                }
                String pcontact=Pcontact.getText().trim();
                String pcon_reg=("^[6-9]{1}[0-9]{9}$");
                if(!(Pattern.matches(pcon_reg, pcontact)))
                {
                    JOptionPane.showMessageDialog(null,"Enter valid contact number");
                    Pcontact.requestFocus();
                    return;
                }
                String paadhar=Paadhar.getText().trim();
                String paad_reg=("^[0-9]{12}$");
                if(!(Pattern.matches(paad_reg,paadhar)))
                {
                    JOptionPane.showMessageDialog(null,"Please enter a valid Aadhar Number");
                    Paadhar.requestFocus();
                    return;
                }
                String sql="INSERT INTO new_patient "
                +"(userid,name,father,gender,age,contact,address,aadhar,disease,registrationd)"
                +"VALUES(?,?,?,?,?,?,?,?,?,?)";
                String url="jdbc:mysql://localhost:3306/hospitalmana";
                Connection conn=DriverManager.getConnection(url,"root","root");
                PreparedStatement ps=conn.prepareStatement(sql);
                ps.setString(1,Puserid.getText());
                ps.setString(2,Pname.getText());
                ps.setString(3,Pfather.getText());
                ps.setString(4,Gender);
                ps.setInt(5,Integer.parseInt(Page.getText()));
                ps.setString(6,Pcontact.getText());
                ps.setString(7,Paddress.getText());
                ps.setString(8,Paadhar.getText());
                ps.setString(9,Pdisease.getText());
                ps.setDate(10,new java.sql.Date(Pregistrationd.getDate().getTime()));
                int a=ps.executeUpdate();
                if(a>0)
                {
                    JOptionPane.showMessageDialog(null,"Patient Add successfully");
                    Puserid.setText(null);
                    Pname.setText(null);
                    Pfather.setText(null);
                    buttonGroup1.clearSelection();
                    Page.setText(null);
                    Pcontact.setText(null);
                    Paddress.setText(null);
                    Paadhar.setText(null);
                    Pdisease.setText(null);
                    Pregistrationd.setDate(null);
        
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Something is wrong check the information");
                }
                ps.close();
                conn.close();
                
            }
            catch(Exception ex)
            {
                JOptionPane.showMessageDialog(null,""+ex);
            }
        }
    }//GEN-LAST:event_SaveActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        Puserid.setText(null);
        Pname.setText(null);
        Pfather.setText(null);
        buttonGroup1.clearSelection();
        Page.setText(null);
        Pcontact.setText(null);
        Paddress.setText(null);
        Paadhar.setText(null);
        Pdisease.setText(null);
        Pregistrationd.setDate(null);
        
    }//GEN-LAST:event_ClearActionPerformed

    private void SearchupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchupdateActionPerformed
        CardLayout cl=(CardLayout)centralpanel.getLayout();
        cl.show(centralpanel, "searchupdate");
    }//GEN-LAST:event_SearchupdateActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        System.exit(0);
    }//GEN-LAST:event_logoutActionPerformed

    private void MaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleActionPerformed
        Gender ="Male";
    }//GEN-LAST:event_MaleActionPerformed

    private void FemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemaleActionPerformed
        Gender="Female";
    }//GEN-LAST:event_FemaleActionPerformed

    private void PatientlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientlistActionPerformed
        CardLayout cl=(CardLayout)centralpanel.getLayout();
        cl.show(centralpanel,"patientlist");
        Patientlisttable();
          filterbydate.getDateEditor().addPropertyChangeListener("date", e -> {
        filterpatientbydate(filterbydate.getDate());
    });
        
    }//GEN-LAST:event_PatientlistActionPerformed

    private void AppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppointmentActionPerformed
        CardLayout cl=(CardLayout)centralpanel.getLayout();
        cl.show(centralpanel,"appointment");
        doctorcombobox();
    }//GEN-LAST:event_AppointmentActionPerformed

    private void Psearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Psearch1ActionPerformed
    if(Auserid.getText().isEmpty())
    {
        JOptionPane.showMessageDialog(null,"Please enter Patient id");
    }
    else
    {
        String userid=Auserid.getText().trim().toUpperCase();
        String Ause_reg=("^[A-Za-z]{3}[0-9]{3,4}$");
        if(Pattern.matches(Ause_reg,userid))
        {
            try
            {
                String sql="SELECT p.name, a.doctor, a.appointment_date, a.appointment_time "+
                        "FROM new_patient p "+
                        "LEFT JOIN appointment a on p.userid=a.userid where p.userid =?";
                String url="jdbc:mysql://localhost:3306/hospitalmana";
                Connection conn=DriverManager.getConnection(url,"root","root");
                PreparedStatement ps=conn.prepareStatement(sql);
                ps.setString(1,Auserid.getText());
                ResultSet rs=ps.executeQuery();
                if(rs.next())
                {
                   // JOptionPane.showMessageDialog(null, "data found");
                    Aname.setText(rs.getString("name"));
                      String d=rs.getString("doctor");
                      Adoctor.setSelectedItem(d);
                      Aappointmentdate.setDate(rs.getDate("appointment_date"));
                      String h=rs.getString("appointment_time");
                      Aappointmenttime.setSelectedItem(h);

                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Data not found");
                }
                ps.close();
                conn.close();
                }
            catch(Exception ex)
            {
                JOptionPane.showMessageDialog(null,""+ex);
            }
        }
    }
    }//GEN-LAST:event_Psearch1ActionPerformed

    private void AsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsaveActionPerformed
       if(Auserid.getText().isEmpty()||
       Adoctor.getSelectedIndex()==0||
       Aappointmentdate.getDate()==null||
       Aappointmenttime.getSelectedIndex()==0)      
        {
            JOptionPane.showMessageDialog(null," Please check all value");
            return ;
        }
       java.sql.Date appointdate=new java.sql.Date(Aappointmentdate.getDate().getTime());
       String doctor=Adoctor.getSelectedItem().toString();
       String slot=Aappointmenttime.getSelectedItem().toString();
       if(!slotavailable(doctor,appointdate,slot))
       {
           JOptionPane.showMessageDialog(null,"This time slot is allready booked \n Please choose another slot");
           return;
       }
        try
        {   
        String sql="insert into appointment( userid,doctor,appointment_date,appointment_time )"+
        "values(?,?,?,? )";
        String url="jdbc:mysql://localhost:3306/hospitalmana";
        Connection conn=DriverManager.getConnection(url,"root","root");
        PreparedStatement ps=conn.prepareStatement(sql);
        ps.setString(1,Auserid.getText().toUpperCase());
        ps.setString(2,Adoctor.getSelectedItem().toString());
        ps.setDate(3,new java.sql.Date(Aappointmentdate.getDate().getTime()));
        ps.setString(4,Aappointmenttime.getSelectedItem().toString());     
        int a=ps.executeUpdate();
        if(a>0)
        {
           JOptionPane.showMessageDialog(null,"Appointment successfully");
              Auserid.setText(null);
              Aname.setText(null);
              Adoctor.setSelectedIndex(0);
              Aappointmentdate.setDate(null);
              Aappointmenttime.setSelectedIndex(0);
        }
        ps.close();
        conn.close();
        }
        catch(Exception ex)
         {
          JOptionPane.showMessageDialog(null," It  is already saved. "+ex);
         } 
    
    }//GEN-LAST:event_AsaveActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
       if(Auserid.getText().isEmpty()||
       Adoctor.getSelectedIndex()==0||
       Aappointmentdate.getDate()==null||
       Aappointmenttime.getSelectedIndex()==0)      
        {
            JOptionPane.showMessageDialog(null," Please check all value");
            return;
        }    
       java.sql.Date appointdate=new java.sql.Date(Aappointmentdate.getDate().getTime());
       String doctor=Adoctor.getSelectedItem().toString();
       String slot=Aappointmenttime.getSelectedItem().toString();
       if(!slotavailable(doctor,appointdate,slot))
       {
           JOptionPane.showMessageDialog(null,"This time slot is allready booked \n Please choose another slot");
           return;
       }
      
    try
    {
        String sql="update appointment set doctor=?,appointment_date=?,appointment_time=? where userid=?";
        String url="jdbc:mysql://localhost:3306/hospitalmana";
        Connection con = DriverManager.getConnection(url,"root","root");
        PreparedStatement ps = con.prepareStatement(sql);
        ps.setString(1,Adoctor.getSelectedItem().toString());
        ps.setDate(2,new java.sql.Date(Aappointmentdate.getDate().getTime()));  
        ps.setString(3, Aappointmenttime.getSelectedItem().toString());
        ps.setString(4,Auserid.getText());
        int a =ps.executeUpdate();
        if(a>0)
        {
            JOptionPane.showMessageDialog(null,"Data update Success.");
            Auserid.setText(null);
            Aname.setText(null);
            Adoctor.setSelectedIndex(0);
            Aappointmentdate.setDate(null);
            Aappointmenttime.setSelectedIndex(0);
            return;
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Error");
        }
        ps.close();
        con.close();
    }
    catch(Exception ex)
    {
        JOptionPane.showMessageDialog(null,""+ex);
    }
    }//GEN-LAST:event_UpdateActionPerformed

    private void AcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcancelActionPerformed
        if(Auserid.getText().isEmpty()||
           Aname.getText().isEmpty()||
           Adoctor.getSelectedIndex()==0||
           Aappointmentdate.getDate()==null||
           Aappointmenttime.getSelectedIndex()==0)
        {
            JOptionPane.showMessageDialog(null,"Please search the patient first");
            return;
        }
        int confirm=JOptionPane.showConfirmDialog(null,"Are you sure you want to cancel this appointment",
                                                        "Confirm Cancel",JOptionPane.YES_NO_OPTION);
        if(confirm==JOptionPane.YES_OPTION)
        {
            try
            {
                String sql="UPDATE appointment SET status='CANCELLED' where userid=?";
                String url="jdbc:mysql://localhost:3306/hospitalmana";
                Connection conn=DriverManager.getConnection(url,"root","root");
                PreparedStatement ps=conn.prepareStatement(sql);
                ps.setString(1,Auserid.getText().toUpperCase());
                int a=ps.executeUpdate();
                if(a>0)
                {
                    JOptionPane.showMessageDialog(null,"Appointment Cancelled");
                    Auserid.setText(null);
                    Aname.setText(null);
                    Adoctor.setSelectedIndex(0);
                    Aappointmentdate.setDate(null);
                    Aappointmenttime.setSelectedIndex(0);
                    return;
                }
                ps.close();
                conn.close();
            }
            catch(Exception ex)
            {
                JOptionPane.showMessageDialog(null,""+ex);
            }
        }
    }//GEN-LAST:event_AcancelActionPerformed

    private void AdoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdoctorActionPerformed

    private void SfatherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SfatherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SfatherActionPerformed

    private void MALEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MALEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MALEActionPerformed

    private void FEMALEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FEMALEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FEMALEActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
    try
        {   
            String Gender = null;

        if (MALE.isSelected()) {
            Gender = "Male";
        } else if (FEMALE.isSelected()) {
            Gender = "Female";
        } else {
            JOptionPane.showMessageDialog(null, "Please select Gender");
            return;
        }

        String sql="UPDATE new_patient  SET name=?,father=?,gender=?,"
        +" age=?, contact=?, address=?, aadhar=?, disease=? ,registrationd=?  "
        +" Where userid = ? ";
        String url="jdbc:mysql://localhost:3306/hospitalmana";
        Connection conn=DriverManager.getConnection(url,"root","root");
        PreparedStatement ps=conn.prepareStatement(sql);
        ps.setString(1,Sname.getText());
        ps.setString(2,Sfather.getText());
        ps.setString(3,Gender);
        ps.setString(4,Sage.getText());
        ps.setString(5,Scontact.getText());
        ps.setString(6,Saddress.getText());
        ps.setString(7,Saadhar.getText());
        ps.setString(8,Sdisease.getText());
        ps.setDate(9,new java.sql.Date (Sregistrationd.getDate().getTime()));
        ps.setString(10,Suserid.getText().toUpperCase());
        int a=ps.executeUpdate();
        if(a>0)
        {
           JOptionPane.showMessageDialog(null,"Update Successfully");
              Suserid.setText(null);
              Sname.setText(null);
              Sfather.setText(null);
              Sage.setText(null);
              Scontact.setText(null);
              buttonGroup2.clearSelection();
              Saddress.setText(null);
              Saadhar.setText(null);
              Sdisease.setText(null);
              Sregistrationd.setDate(null);
             
        }
    }
    catch(Exception ex)
    {
        JOptionPane.showMessageDialog(null,""+ex);
    }
    }//GEN-LAST:event_updateActionPerformed

    private void Clear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clear1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Clear1ActionPerformed

    private void SsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SsearchActionPerformed
    if(Suserid.getText().isEmpty())
    {
        JOptionPane.showMessageDialog(null,"Please enter the userid");
    }
    else
    {
        String suserid=Suserid.getText().trim().toUpperCase();
        String suse_reg=("^[A-Za-z]{3}[0-9]{3,4}$");
        if((Pattern.matches(suse_reg, suserid)))
            {
                try
                {
                    String sql="SELECT *FROM new_patient where userid=?";
                    String url="jdbc:mysql://localhost:3306/hospitalmana";
                    Connection conn=DriverManager.getConnection(url,"root","root");
                    PreparedStatement ps=conn.prepareStatement(sql);
                    ps.setString(1,suserid);
                    ResultSet rs=ps.executeQuery();
                    if(rs.next())
                    {
                        JOptionPane.showMessageDialog(null,"Data found");
                        Sname.setText(rs.getString("name").trim());
                        Sfather.setText(rs.getString("father").trim());
                        String h=rs.getString("gender").trim();
                        if(h.equalsIgnoreCase("Male"))
                        {
                           MALE.setSelected(true);
                        }
                        else
                        {
                           FEMALE.setSelected(true);
                        }
                        Sage.setText(rs.getString("age"));
                        Scontact.setText(rs.getString("contact").trim());
                        Saadhar.setText(rs.getString("aadhar").trim());
                        Saddress.setText(rs.getString("address").trim());
                        Sdisease.setText(rs.getString("disease"));
                        Sregistrationd.setDate(rs.getDate("registrationd"));
                      
                    }
                    else
                    {
                       JOptionPane.showMessageDialog(null,"Data not found");
                       Suserid.setText(null);
                    }
                    rs.close();
                    ps.close();
                    conn.close();
                   }                   
                catch(Exception ex)
                {
                    JOptionPane.showMessageDialog(null,"error"+ex);
                }
            }
        else
        {
               JOptionPane.showMessageDialog(null,"Please enter a valid userid");
        }
    }
    }//GEN-LAST:event_SsearchActionPerformed
    private boolean slotavailable(String doctor,java.sql.Date date,String timeslot )
    {
        boolean available=true;
        try
        {
            String sql="SELECT COUNT(*)FROM appointment where doctor=? and appointment_date=? and appointment_time=? and status='BOOKED'";
            String url="jdbc:mysql://localhost:3306/hospitalmana";
            Connection conn=DriverManager.getConnection(url,"root","root");
            PreparedStatement ps=conn.prepareStatement(sql);
            ps.setString(1,doctor);
            ps.setDate(2,date);
            ps.setString(3,timeslot);
            ResultSet rs=ps.executeQuery();
            if(rs.next()&& rs.getInt(1)>0)
            {
                available=false;
            }
            rs.close();
            ps.close();
            conn.close();
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,""+ex);
        }
        return available;
    }
    private String generatepatientid()//shivam
    {
        String newid="PAT001";
        try
        {
            String sql="SELECT userid FROM new_patient ORDER BY userid DESC LIMIT 1";
            String url="jdbc:mysql://localhost:3306/hospitalmana";
            Connection conn=DriverManager.getConnection(url,"root","root");
            PreparedStatement ps=conn.prepareStatement(sql);
            ResultSet rs=ps.executeQuery();
            if(rs.next())
            {
                String lastid=rs.getString("userid");
                int num=Integer.parseInt(lastid.substring(3));
                newid="PAT"+String.format("%03d",num+1);
            }  
            rs.close();
            ps.close();
            conn.close();
            
        }
            
        catch(Exception ex)
            {
            JOptionPane.showMessageDialog(null,""+ex);
            }
        return newid;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(receptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(receptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(receptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(receptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new receptionist().setVisible(true);
            }
        });
    }
    private String Gender;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Aappointmentdate;
    private javax.swing.JComboBox<String> Aappointmenttime;
    private javax.swing.JButton Acancel;
    private javax.swing.JComboBox<String> Adoctor;
    private javax.swing.JTextField Aname;
    private javax.swing.JButton Appointment;
    private javax.swing.JButton Asave;
    private javax.swing.JTextField Auserid;
    private javax.swing.JButton Clear;
    private javax.swing.JButton Clear1;
    private javax.swing.JRadioButton FEMALE;
    private javax.swing.JRadioButton Female;
    private javax.swing.JButton Home;
    private javax.swing.JRadioButton MALE;
    private javax.swing.JRadioButton Male;
    private javax.swing.JButton Newpatient;
    private javax.swing.JTextField Paadhar;
    private javax.swing.JLabel Padd;
    private javax.swing.JLabel Padd1;
    private javax.swing.JTextField Paddress;
    private javax.swing.JTextField Page;
    private javax.swing.JButton Patientlist;
    private javax.swing.JTextField Pcontact;
    private javax.swing.JTextField Pdisease;
    private javax.swing.JTextField Pfather;
    private javax.swing.JTextField Pname;
    private com.toedter.calendar.JDateChooser Pregistrationd;
    private javax.swing.JButton Psearch1;
    private javax.swing.JTextField Puserid;
    private javax.swing.JTextField Saadhar;
    private javax.swing.JTextField Saddress;
    private javax.swing.JTextField Sage;
    private javax.swing.JButton Save;
    private javax.swing.JTextField Scontact;
    private javax.swing.JTextField Sdisease;
    private javax.swing.JButton Searchupdate;
    private javax.swing.JTextField Sfather;
    private javax.swing.JTextField Sname;
    private com.toedter.calendar.JDateChooser Sregistrationd;
    private javax.swing.JButton Ssearch;
    private javax.swing.JTextField Suserid;
    private javax.swing.JButton Update;
    private javax.swing.JPanel appointment;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JPanel centralpanel;
    private com.toedter.calendar.JDateChooser filterbydate;
    private javax.swing.JPanel footer;
    private javax.swing.JPanel header;
    private javax.swing.JPanel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jlabeldate;
    private javax.swing.JLabel jtodaypatient;
    private javax.swing.JLabel jtotalpatient;
    private javax.swing.JButton logout;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel newpatient;
    private javax.swing.JPanel patientlist;
    private javax.swing.JPanel searchupdate;
    private javax.swing.JTable tabletodayappointment;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
